/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-09 16:33:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=euc-kr");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<title>Mr.Bread</title>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("   function changeMap() {\r\n");
      out.write("      if (map.style.visibility == \"visible\")\r\n");
      out.write("         map.style.visibility = \"hidden\";\r\n");
      out.write("      else\r\n");
      out.write("         map.style.visibility = \"visible\";\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />\r\n");
      out.write("   <div id=\"container\">\r\n");
      out.write("      <div>\r\n");
      out.write("         <ul class=\"h\">\r\n");
      out.write("            <li class=\"h\"><a class=\"h\" href=\"home.jsp\">HOME</a></li>\r\n");
      out.write("            <li class=\"h\"><a class=\"h\" href=\"content.jsp\">CONTENT</a></li>\r\n");
      out.write("            <li class=\"h\"><a class=\"h\" href=\"order.jsp\">ORDER</a></li>\r\n");
      out.write("            <li class=\"h\"><a class=\"h\" href=\"about.jsp\">ABOUT</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br /> <br /> <br />\r\n");
      out.write("      <div id=\"main\">\r\n");
      out.write("         <br />\r\n");
      out.write("         <p class=\"p1\">Brand Story</p>\r\n");
      out.write("         <hr width=\"15%\" style=\"border: 1px solid darkred\" />\r\n");
      out.write("         <table border=\"0\" align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td><img class=\"img1\" src=\"21.jpg\" /></td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <div id=\"p2\">\r\n");
      out.write("                     <p class=\"p2\">\r\n");
      out.write("                        Healthy baked goods <br /> with the purest and <br /> finest\r\n");
      out.write("                        ingredients. <br /> <br /> Mr.Bread : <br /> A European\r\n");
      out.write("                        styled bakery- <br /> A friendly service to your home, your\r\n");
      out.write("                        family, <br /> and to your neighbors. <br /> <br />\r\n");
      out.write("                        Mr.Bread's bread : <br /> Baked like your fathers goods… <br />\r\n");
      out.write("                        only with fresh and pure <br /> natural ingredients <br />\r\n");
      out.write("                     </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <div id=\"p3\">\r\n");
      out.write("                     <p class=\"p3\">\r\n");
      out.write("                        Mr.Bread is a group of people <br /> who are passionate some\r\n");
      out.write("                        would say, <br /> obsessed with creating <br /> exceptional\r\n");
      out.write("                        artisan breads. <br /> <br /> It‘s why we find carefully\r\n");
      out.write("                        sourced, <br /> top-quality ingredients, used according to <br />\r\n");
      out.write("                        recipes and processes that <br /> have been perfected over\r\n");
      out.write("                        generations. <br /> <br /> Read on to learn about <br /> our\r\n");
      out.write("                        incredibly detailed approach. <br />\r\n");
      out.write("                     </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td><img class=\"img2\" src=\"20.jpg\" /></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("         <hr width=\"98%\" style=\"border: 0.5px solid #b76d39\" />\r\n");
      out.write("         <br /> <br />\r\n");
      out.write("         <p class=\"p1\">Location</p>\r\n");
      out.write("         <hr width=\"11%\" style=\"border: 1px solid darkred\" />\r\n");
      out.write("         <br> <br> <br>\r\n");
      out.write("         <table border=\"0\" align=\"center\" width=\"700\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <center>\r\n");
      out.write("                     <p class=\"p5\">Address : 23-2, Bangi-dong, Songpa-gu, Seoul,\r\n");
      out.write("                        Korea</p>\r\n");
      out.write("                  </center>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <center>\r\n");
      out.write("                     <center>\r\n");
      out.write("                        <br><p class=\"p5\">need any map?</p>\r\n");
      out.write("                     </center>\r\n");
      out.write("                     <input type=\"checkbox\" name=\"ck\" value=\"2\" onclick=\"changeMap()\" />\r\n");
      out.write("\r\n");
      out.write("                     <div id=\"map\">\r\n");
      out.write("                        <img src=\"map.jpg\" width=\"700\" height=\"480\" />\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </center>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
